{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "a3s-box.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a3s-box.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "a3s-box.serviceAccountName" . }}
  labels:
    {{- include "a3s-box.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "a3s-box.serviceAccountName" . }}
  labels:
    {{- include "a3s-box.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "a3s-box.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "a3s-box.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
