/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Model configuration */
export interface ModelConfig {
  provider: string
  name: string
  baseUrl?: string
  apiKey?: string
}
/** Resource configuration */
export interface ResourceConfig {
  vcpus: number
  memoryMb: number
  diskMb: number
  timeout: number
}
/** Lane configuration */
export interface LaneConfig {
  minConcurrency: number
  maxConcurrency: number
}
/** Box configuration */
export interface BoxConfig {
  workspace?: string
  skills?: Array<string>
  model?: ModelConfig
  resources?: ResourceConfig
  lanes?: Record<string, LaneConfig>
  logLevel?: string
  debugGrpc?: boolean
}
/** Token usage */
export interface TokenUsage {
  promptTokens: number
  completionTokens: number
  totalTokens: number
}
/** Generate result */
export interface GenerateResult {
  text: string
  usage: TokenUsage
}
/** Session configuration */
export interface SessionConfig {
  system?: string
  contextThreshold?: number
  contextStrategy?: string
}
/** Create a box (convenience function) */
export declare function createBox(config?: BoxConfig | undefined | null): Promise<Box>
export type A3sBox = Box
/** A3S Box - main entry point */
export declare class Box {
  /** Create a new box */
  static new(config?: BoxConfig | undefined | null): A3SBox
  /** Create a session */
  createSession(config?: SessionConfig | undefined | null): Session
  /** List sessions */
  listSessions(): Array<string>
  /** Destroy the box */
  destroy(): Promise<void>
  /** Get queue status */
  queueStatus(): Promise<string>
  /** Get metrics */
  metrics(): Promise<string>
}
/** Session */
export declare class Session {
  /** Get session ID */
  get sessionId(): string
  /** Generate (non-streaming) */
  generate(prompt: string): Promise<GenerateResult>
  /** Stream (streaming) */
  stream(prompt: string): Promise<void>
  /** Generate object (structured output) */
  generateObject(prompt: string, schema: string): Promise<string>
  /** Use skill */
  useSkill(skillName: string): Promise<void>
  /** Remove skill */
  removeSkill(skillName: string): Promise<void>
  /** List active skills */
  listSkills(): Promise<Array<string>>
  /** Compact context */
  compact(): Promise<void>
  /** Clear context */
  clear(): Promise<void>
  /** Configure session */
  configure(thinking?: boolean | undefined | null, budget?: number | undefined | null, model?: ModelConfig | undefined | null): Promise<void>
  /** Get context usage */
  contextUsage(): Promise<string>
  /** Get history */
  history(): Promise<string>
  /** Destroy session */
  destroy(): Promise<void>
}
